spring:
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    username: intern
    password: Gabia43701!!
    url: jdbc:mysql://seat_mysql:3306/intern?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true


logging:
  level:
    org.springframework.security: DEBUG
    org:
      hibernate:
        type: trace


#facebook:
#  client:
#    clientId: <your-client-id>
#    clientSecret: <your-secret>
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id, name, email, picture

google :
  client :
    clientId : 898505969152-hkcf91qo3gkj0jfjtshni5duqbe0uqc0.apps.googleusercontent.com
    clientSecret: 6RBgEZXwPTXijKHmvgqfKGDo
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

server:
  ssl:
    key-store: keystore.p12
    key-store-password: cheese
    keyStoreType: PKCS12
    keyAlias: tomcat


  redis:
    host:localhost
    port:6379